"""Is dAIC = 8.8 for M_global over M_local_RAR something a NEWTONIAN universe
produces on its own?

The programme's standing objection -- "detector calibration is conditional, not
general" -- applies to model selection as much as to detection.  Section 4 of
REPORT.md reports dAIC(global - RAR) = 8.8 and dAIC(global - Newton) = 17.9 on
the real data.  This script measures the null distribution of both, on Newtonian
synthetic universes generated by exactly the machinery of `inject_recover.py`.

The scoring code below is a minimal copy of `model_compare.py`'s.  A GATE at the
top asserts that it reproduces `model_compare.json`'s AIC values on the REAL
data to 0.05, so the copy cannot have drifted.
"""
from __future__ import annotations

import json
import os
import sys
import time

import numpy as np
from scipy.optimize import minimize
from scipy.special import i0, i1, k0, k1

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import vaudit_core as V                                       # noqa: E402
import adyn_model as M                                        # noqa: E402
import inject_recover as IR                                   # noqa: E402

G = M.G
XG, UG, NR = V.XG, V.UG, len(V.XG)
A0_RAR = V.FIT["rar"]
GP = np.linspace(-1.2, 0.6, 37)
FID = dict(zU=np.log10(0.60), sc=0.15, dhz=0.0, kv=1.5, al=0.60,
           lfg=np.log10(0.25), fhg=2.0, fhzg=0.5, lo=0.3, hi=2.0)


def observables(B, kind, theta=None, C=None, lSig=None):
    """Identical to model_compare.observables for kinds newton/rar/global."""
    C = C or FID
    NG = B.NG
    Ups = 10 ** (C["zU"] + C["sc"] * (B.BK - 3.4))
    hz = B.HZ_TAB * 10 ** C["dhz"]
    fg = np.full(NG, 10 ** C["lfg"])
    al = np.full(NG, C["al"])
    base = B.newton_chain(Ups, hz, fg, al, C["kv"], C["fhg"], C["fhzg"])
    if kind == "newton":
        bz = np.ones((NG, NR))
    else:
        prof = base["prof"]
        w = np.interp(UG, prof.u, prof.w)
        Cs = np.interp(UG, prof.u, prof.Cn, left=0.0, right=1.0)
        pg = M.profile_for_k(2.0)
        Cg = np.interp(UG / base["f_hzg"], pg.u, pg.Cn, left=0.0, right=1.0)
        hzm, Rr, gRN, Vc2N = base["hz"], base["R"], base["gR"], base["Vc2"]
        zz = UG[None, None, :] * hzm[:, :, None]
        Sig_lt = (base["Sig_s"][:, :, None] * Cs[None, None, :]
                  + base["Sig_g"][:, :, None] * Cg[None, None, :])
        dN = (np.gradient(Vc2N, XG, axis=1) / (B.hR_m * Rr))[:, :, None]
        KzN = np.maximum(2 * np.pi * G * Sig_lt - zz * dN, 1e-30)
        if kind == "rar":
            Kz = M.nu_rar(np.sqrt(gRN[:, :, None] ** 2 + KzN ** 2) / A0_RAR) * KzN
        elif kind == "global":
            f = 10 ** (theta[0] * (lSig - lSig.mean()))
            Kz = KzN * f[:, None, None]
        else:
            raise KeyError(kind)
        s2 = np.trapezoid(w[None, None, :] * Kz, zz, axis=2)
        s2n = np.trapezoid(w[None, None, :] * KzN, zz, axis=2)
        bz = s2 / s2n
    sl = B.to_los(np.sqrt(base["s2"] * bz) / 1e3, al)
    a_, h_ = M.fit_exponential_rows(XG, sl, C["lo"], C["hi"])
    return a_, h_ * np.squeeze(B.hR_as)


def _inner(a_, h_, la_o, lh_o, sa_o, sh_o):
    la_m, lh_m = np.log10(a_), np.log10(h_)

    def nll(t):
        c, lsa, lsh = t
        va = sa_o ** 2 + np.exp(2 * lsa)
        vh = sh_o ** 2 + np.exp(2 * lsh)
        ra, rh = la_o - (la_m + c), lh_o - lh_m
        return 0.5 * float(np.sum(ra ** 2 / va + np.log(va)
                                  + rh ** 2 / vh + np.log(vh)))
    best = None
    for c0 in (float(np.mean(la_o - la_m)), 0.0):
        m = minimize(nll, [c0, np.log(0.12), np.log(0.12)],
                     method="Nelder-Mead",
                     options=dict(maxiter=4000, xatol=1e-9, fatol=1e-11))
        if best is None or m.fun < best.fun:
            best = m
    return float(best.fun)


def aic(B, kind, la_o, lh_o, sa_o, sh_o, grid=None, lSig=None):
    if grid is None:
        return 2 * _inner(*observables(B, kind), la_o, lh_o, sa_o, sh_o) + 2 * 3
    best = None
    for t in grid:
        a_, h_ = observables(B, kind, [t], lSig=lSig)
        if not (np.all(np.isfinite(a_)) and np.all(np.isfinite(h_))
                and np.all(a_ > 0) and np.all(h_ > 0)):
            continue
        f = _inner(a_, h_, la_o, lh_o, sa_o, sh_o)
        if best is None or f < best:
            best = f
    return 2 * best + 2 * 4


# ------------------------------------------------------------------- the GATE
B0 = V.Bench()
lS0 = B0.log_sigma0()
la_o, lh_o = np.log10(B0.OBS_AMP), np.log10(B0.OBS_H)
sa_o = B0.OBS_EAMP / B0.OBS_AMP / np.log(10)
sh_o = B0.OBS_EH / B0.OBS_H / np.log(10)
real = {"M_Newton": aic(B0, "newton", la_o, lh_o, sa_o, sh_o),
        "M_local_RAR": aic(B0, "rar", la_o, lh_o, sa_o, sh_o),
        "M_global": aic(B0, "global", la_o, lh_o, sa_o, sh_o, GP, lS0)}
ref = json.load(open(os.path.join(HERE, "model_compare.json")))["item4_model_comparison"]
print("  GATE: this script's AIC vs model_compare.json on the REAL data")
ok = True
for k, v in real.items():
    d = abs(v - ref[k]["aic"])
    ok &= d < 0.05
    print(f"    {k:<14}{v:>10.2f}{ref[k]['aic']:>10.2f}   |d| = {d:.3f}"
          f"   {'PASS' if d < 0.05 else 'FAIL'}")
assert ok, "the scoring copy has drifted from model_compare.py"
D_RAR = real["M_local_RAR"] - real["M_global"]
D_NEW = real["M_Newton"] - real["M_global"]
print(f"    observed dAIC(RAR - global)    = {D_RAR:.2f}")
print(f"    observed dAIC(Newton - global) = {D_NEW:.2f}")

# ----------------------------- nulls under BOTH hypotheses, not just Newton
# Under Newton-truth, RAR is penalised for a trend that is not there, so a large
# dAIC(RAR - global) is the EXPECTATION, not evidence.  Under RAR-truth it must
# be near zero.  The observed value is only interpretable between the two.
NT = int(os.environ.get("VAUDIT_NULL_TRIALS", "150"))
inj = IR.Injector(ndraw_inner=1)
e_hs = B0.OBS_EH.copy()
RES = {}


def run_null(truth, ntrial, seed):
    rng = np.random.default_rng(seed)
    t0 = time.time()
    dr, dn = [], []
    for it in range(ntrial):
        C_t = V.Bench.draw_common(rng)
        NG = inj.NG
        lU = C_t["zU"] + C_t["sc"] * (B0.BK - 3.4) \
            + rng.normal(0, M.FID["s_Upsilon_gal"], NG)
        lfg = C_t["lfg"] + rng.normal(0, 0.15, NG)
        al = np.full(NG, C_t["al"])
        d_lhR = rng.normal(0.0, inj.e_lhR)
        d_lSig = -2.0 * d_lhR
        d_lhz = IR.BERSHADY_EXP * d_lhR + rng.normal(0.0, inj.s_rel)
        # TRUE universe, generated on the LATENT photometry
        Ct = dict(C_t, zU=C_t["zU"], sc=C_t["sc"])
        a_t, h_t = observables(inj.T, "newton" if truth == "newton" else "rar",
                               C=Ct)
        a_ob = np.maximum(a_t + rng.normal(0.0, inj.e_sig), 1.0)
        h_ob = np.maximum(h_t + rng.normal(0.0, e_hs), 1.0)
        # OBSERVED photometry
        Bo = V.Bench(mu0K=inj.mu0_true - d_lSig / 0.4,
                     hR_as=inj.hR_true * 10 ** d_lhR,
                     hz_kpc=inj.hz_true * 10 ** d_lhz, apc=inj.ref.APC)
        lS = Bo.log_sigma0()
        lao, lho = np.log10(a_ob), np.log10(h_ob)
        sa = inj.e_sig / a_ob / np.log(10)
        sh = e_hs / h_ob / np.log(10)
        an = aic(Bo, "newton", lao, lho, sa, sh)
        ar = aic(Bo, "rar", lao, lho, sa, sh)
        ag = aic(Bo, "global", lao, lho, sa, sh, GP, lS)
        dr.append(ar - ag)
        dn.append(an - ag)
        if (it + 1) % 25 == 0:
            print(f"      {truth} trial {it+1}/{ntrial}  "
                  f"({time.time()-t0:.0f}s)", flush=True)
    return np.array(dr), np.array(dn)


ub = float(1 - 0.05 ** (1 / NT))
for truth in ("newton", "rar"):
    dr, dn = run_null(truth, NT, 90210 if truth == "newton" else 31337)
    p_r = float(np.mean(dr >= D_RAR))
    p_n = float(np.mean(dn >= D_NEW))
    print(f"\n  {truth.upper()}-TRUTH NULL, {NT} synthetic universes, "
          f"full covariance")
    print(f"    dAIC(RAR - global)    median {np.median(dr):+.2f}"
          f"  95% [{np.percentile(dr,2.5):+.2f},{np.percentile(dr,97.5):+.2f}]"
          f"   P(>= {D_RAR:.1f} observed) = {p_r:.4f}")
    print(f"    dAIC(Newton - global) median {np.median(dn):+.2f}"
          f"  95% [{np.percentile(dn,2.5):+.2f},{np.percentile(dn,97.5):+.2f}]"
          f"   P(>= {D_NEW:.1f} observed) = {p_n:.4f}")
    RES[truth] = dict(
        dAIC_RAR_minus_global=dict(
            median=float(np.median(dr)), p2p5=float(np.percentile(dr, 2.5)),
            p97p5=float(np.percentile(dr, 97.5)), min=float(dr.min()),
            max=float(dr.max()), p_ge_observed=p_r),
        dAIC_Newton_minus_global=dict(
            median=float(np.median(dn)), p2p5=float(np.percentile(dn, 2.5)),
            p97p5=float(np.percentile(dn, 97.5)), min=float(dn.min()),
            max=float(dn.max()), p_ge_observed=p_n))
print(f"\n    (95% upper bound on a zero count with {NT} trials: {ub:.4f})")
out = dict(observed_dAIC_RAR_minus_global=D_RAR,
           observed_dAIC_Newton_minus_global=D_NEW,
           n_trials=NT, nulls=RES, upper_bound_zero_count=ub,
           gate_aic_reproduction={k: [v, ref[k]["aic"]] for k, v in real.items()})
with open(os.path.join(HERE, "model_null.json"), "w") as fh:
    json.dump(out, fh, indent=1)
print("\n  wrote model_null.json")
