"""Power and empirical calibration of the field-law anisotropy detector.

Run O reported "injection recovery 2/2 at 10% noise" and a 4.2% false-positive
rate from 24 scalar-only trials. Neither is a power characterisation. 2 of 2 has
a 95% interval running from 0.16 to 1.00, and a rate estimated from 24 trials has
a standard error of about 4 percentage points, which is the size of the quantity
being estimated.

This module replaces both with a proper measurement, over a grid spanning the
things that actually change the answer:

    response amplitude      how strong the injected anisotropy is
    source axis ratio       how far from spherical the configuration is, which
                            the spherical blindness theorem says is the variable
                            that decides whether anisotropy is visible AT ALL
    preferred-axis tilt     whether the injected axis aligns with the source's
                            own principal axes or cuts across them
    measurement noise       on the observable, not on the source

and it reports two surfaces rather than two numbers: the POWER to detect a real
anisotropy, and the FALSE-POSITIVE RATE for claiming one from scalar-only data.

THE CALIBRATED STATISTIC

A bare argmin over blind RMS is the wrong detector, because the anisotropic
family NESTS the scalar one -- the richer model can only tie or win, so "a tensor
atom appears in the winner" is guaranteed at some rate with no physics. The
controls lane measured this directly: argmin identifies 4 of 5 injected families
where a one-standard-error parsimony rule gets 5 of 5.

So the statistic here is the IMPROVEMENT from admitting anisotropic atoms,

    D = RMS(scalar atoms only) - RMS(all atoms)

compared against its own null distribution, generated by running the identical
procedure on scalar-only injections at the same amplitude and noise. The reported
p is the fraction of null D at least as large as the observed one, and the
EMPIRICAL CRITICAL VALUE p* satisfying P(p <= p* | H0) = 0.05 is measured rather
than assumed to be 0.05. That is the correct repair for a detector whose nominal
size is wrong -- declaring a stricter threshold like p <= 0.02 is a guess, and it
may be too strict or still too permissive.
"""
from __future__ import annotations

import json
import math
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from field_grammar import GPU, KPC, MSUN, FieldBank, sphericity, xp   # noqa
from field_search import Search, observables, is_tensor              # noqa
from qumond_degeneracy import independent_atoms                      # noqa

HERE = os.path.dirname(os.path.abspath(__file__))


def source(n=48, L_kpc=400.0, axis=(1.0, 0.75, 0.5), rs_kpc=80.0, tilt=0.0):
    """Triaxial source, optionally rotated so its axes do not align with the grid."""
    L = L_kpc * KPC
    h = L / n
    ax = (xp.arange(n) - n / 2 + 0.5) * h
    X = ax[:, None, None] * xp.ones((1, n, n))
    Y = xp.ones((n, 1, n)) * ax[None, :, None]
    Z = xp.ones((n, n, 1)) * ax[None, None, :]
    if tilt != 0.0:
        c, s = math.cos(tilt), math.sin(tilt)
        X, Z = c * X - s * Z, s * X + c * Z
    q = xp.sqrt((X / axis[0]) ** 2 + (Y / axis[1]) ** 2 + (Z / axis[2]) ** 2)
    rho = xp.exp(-(q / (rs_kpc * KPC)) ** 2)
    rho *= 1e14 * MSUN / float(rho.sum() * h ** 3)
    return rho, h


class Config:
    """One source geometry: bank, deduplicated atom split, and design matrix."""

    def __init__(self, axis, tilt, dhat, n=48):
        rho, h = source(n=n, axis=axis, tilt=tilt)
        self.axis_ratio = sphericity(rho, h)
        self.bank = FieldBank(rho, h, dhat=dhat, verbose=False)
        groups, _ = independent_atoms(self.bank)
        keep = [g[0] for g in groups]
        keep = [i for i in keep
                if self.bank.meta[i].split(" x ")[-1] != "gg"]
        self.meta = [self.bank.meta[i] for i in keep]
        y0, Afull, npt = observables(self.bank)
        self.y0 = y0
        self.A = Afull[xp.asarray(np.array(keep, dtype=np.int64))]
        self.npt = npt
        self.tens = [i for i, m in enumerate(self.meta) if is_tensor(m)]
        self.scal = [i for i, m in enumerate(self.meta) if not is_tensor(m)]
        self.S_all = Search(self.A)
        self.S_sca = Search(self.A[xp.asarray(np.array(self.scal,
                                                      dtype=np.int64))])
        self.sd0 = float(xp.std(self.y0))


def statistic(cfg, y):
    """D = RMS(scalar only) - RMS(all atoms), both at k = 2, exhaustive."""
    cfg.S_all.set_target(y - cfg.y0)
    cfg.S_sca.set_target(y - cfg.y0)
    r_all, _ = cfg.S_all.exhaustive_k(2)
    r_sca, _ = cfg.S_sca.exhaustive_k(2)
    return r_sca - r_all


def draw(cfg, rng, kind, amp, noise):
    """Inject a two-term law OFF the bank's parameter grid, then add noise.

    The first version of this module injected laws built from the bank's own
    atoms. For a scalar-only null that makes the truth EXACTLY representable by
    the scalar basis, so admitting anisotropic atoms improves nothing, D is
    identically zero, and the critical value collapses to zero -- at which point
    every trial "detects" and the power is 1.00 by construction.

    A null in which the truth lies exactly in the model's basis is not a null,
    it is a best case. Real physics is never exactly in the basis. So the
    injection is built at scales BETWEEN the bank's grid points (the bank uses
    0.3, 1.0, 3.0; the injection uses 0.55 and 1.8), which leaves an
    irreducible misspecification for both bases to compete over -- which is the
    situation the detector will actually face.
    """
    from field_grammar import SHAPES, tensor_basis, tidal_tensor, nu_rar, A0
    b = cfg.bank
    T, _, _ = tidal_tensor(b.Phi_N, b.h)
    B = tensor_basis(b.inv, b.gvec, b.gmag, T, (0, 0, 1))
    names = [k for k in B if k != "gg"]
    bnames = ([k for k in names if k != "I"] if kind == "tensor" else ["I"])
    gx, gy, gz = b.gvec
    nu = nu_rar(b.gmag / A0)
    y = cfg.y0.copy()
    for sgn, sc in ((1.0, 0.55), (-0.6, 1.8)):
        iname = list(b.inv)[rng.integers(len(b.inv))]
        sname, f = SHAPES[rng.integers(len(SHAPES))]
        w = f(b.inv[iname] / sc)
        w = w - xp.mean(w)
        sd = float(xp.std(w))
        if sd < 1e-12:
            continue
        w = w / sd
        comp = B[bnames[rng.integers(len(bnames))]]
        c = tuple(w * ci for ci in comp)
        k11, k22, k33, k12, k13, k23 = c
        vx = nu * (k11 * gx + k12 * gy + k13 * gz)
        vy = nu * (k12 * gx + k22 * gy + k23 * gz)
        vz = nu * (k13 * gx + k23 * gy + k33 * gz)
        from field_grammar import div
        R = b.P.solve(div(vx, vy, vz, b.h))
        o = _obs_of(cfg, R)
        y = y + sgn * amp * cfg.sd0 * o / (float(xp.std(o)) + 1e-30)
    return y + xp.asarray(rng.normal(0, noise * cfg.sd0, y.size))


def _obs_of(cfg, Psi):
    """The same observable vector the search sees, for one response field."""
    b = cfg.bank
    n, h = b.n, b.h
    ax = (xp.arange(n) - n / 2 + 0.5) * h
    X = ax[:, None] * xp.ones((1, n))
    Y = xp.ones((n, 1)) * ax[None, :]
    R = xp.sqrt(X ** 2 + Y ** 2)
    m = (R > 20 * KPC) & (R < 140 * KPC)
    a = xp.gradient(Psi, h, axis=0)[:, :, n // 2]
    bb = xp.gradient(Psi, h, axis=1)[:, :, n // 2]
    v = ((X * a + Y * bb) / (R + 1e-30))[m]
    S = Psi.sum(axis=2) * h
    d1 = xp.gradient(S, h, axis=0)
    d2 = xp.gradient(S, h, axis=1)
    d = xp.sqrt(d1 ** 2 + d2 ** 2)[m]
    s1 = float(xp.std(v)) + 1e-300
    s2 = float(xp.std(d)) + 1e-300
    return xp.concatenate([v / s1, d / s2])


def main():
    print("=" * 78)
    print("FIELD DETECTOR -- power surface and empirical critical value")
    print("=" * 78)
    NNULL = int(os.environ.get("NNULL", 120))
    NSIG = int(os.environ.get("NSIG", 40))
    rng = np.random.default_rng(20260904)

    GEOM = [
        ("strongly triaxial", (1.0, 0.75, 0.50), 0.0),
        ("mildly triaxial",   (1.0, 0.90, 0.80), 0.0),
        ("near-spherical",    (1.0, 0.97, 0.95), 0.0),
        ("triaxial, tilted",  (1.0, 0.75, 0.50), 0.6),
    ]
    AMPS = (0.05, 0.15, 0.35)
    NOISE = (0.02, 0.10, 0.30)

    out = {"n_null": NNULL, "n_signal": NSIG, "grid": [], "pstar": {}}
    t0 = time.time()
    for gname, axis, tilt in GEOM:
        cfg = Config(axis, tilt, dhat=(0, 0, 1))
        print(f"\n   geometry: {gname}   axis ratio {cfg.axis_ratio:.3f}   "
              f"{len(cfg.meta)} atoms ({len(cfg.tens)} anisotropic)")
        if cfg.axis_ratio > 0.97:
            print("      (spherical blindness theorem: anisotropy is not")
            print("       observable here; this row is the control that shows it)")
        for noise in NOISE:
            # --- the null: scalar-only injections at this noise
            nullD = np.array([statistic(cfg, draw(cfg, rng, "scalar", 0.25,
                                                  noise))
                              for _ in range(NNULL)])
            # empirical critical value: the 95th percentile of the null D
            Dstar = float(np.percentile(nullD, 95))
            # nominal-rule false positive: "a tensor atom appears in the winner"
            fp_naive = 0
            for _ in range(30):
                y = draw(cfg, rng, "scalar", 0.25, noise)
                cfg.S_all.set_target(y - cfg.y0)
                _, idx = cfg.S_all.exhaustive_k(2)
                if any(is_tensor(cfg.meta[i]) for i in idx):
                    fp_naive += 1
            row = {"geometry": gname, "axis_ratio": cfg.axis_ratio,
                   "noise": noise, "D_null_median": float(np.median(nullD)),
                   "D_star_95": Dstar,
                   "fpr_naive_rule": fp_naive / 30.0, "power": {}}
            print(f"      noise {noise:4.0%}   null D median "
                  f"{np.median(nullD):+.3e}, D* (95th) {Dstar:.3e}   "
                  f"naive-rule FPR {fp_naive/30.0:.0%}")
            for amp in AMPS:
                hits = 0
                for _ in range(NSIG):
                    D = statistic(cfg, draw(cfg, rng, "tensor", amp, noise))
                    hits += int(D > Dstar)
                row["power"][str(amp)] = hits / NSIG
                print(f"         amplitude {amp:4.2f}   calibrated power = "
                      f"{hits/NSIG:.2f}")
            out["grid"].append(row)
    print(f"\n   elapsed {time.time()-t0:.0f}s")

    print("\n" + "=" * 78)
    print("   READING THIS")
    print("   D* is the EMPIRICAL critical value, the 95th percentile of the")
    print("   statistic under scalar-only data at that noise. A detector using")
    print("   it is correctly sized by construction, which a nominal p <= 0.05")
    print("   was not, and which a guessed p <= 0.02 would also not be.")
    print("   The naive-rule FPR column is what 'a tensor atom appeared in the")
    print("   winner' costs: it is the rate the nested family guarantees.")
    print("   The near-spherical row is the control the spherical blindness")
    print("   theorem predicts: power there should collapse regardless of")
    print("   amplitude, because the transverse eigenvalue is unobservable.")
    with open(os.path.join(HERE, "field_power.json"), "w") as f:
        json.dump(out, f, indent=1)
    print("\n   written: field_power.json")


if __name__ == "__main__":
    main()
