"""Explicit Gaussian-resolution and imposed missing-cell source alternatives."""
import hashlib,json,time
from pathlib import Path
import numpy as np
from scipy.signal import fftconvolve
from scipy.ndimage import zoom
from threadpoolctl import threadpool_limits
from astropy.io import fits
from mond_atlas_source_resolution import cell_projection_matrix,project,fit_fixed_image
R=Path(__file__).resolve().parents[1];P=R/'work/gravity-first-principles/mond-atlas-source-sensitivity-001';PRIVATE=R/'work/private/mond-atlas-source-sensitivity-001'
def save(p,x):p.write_text(json.dumps(x,indent=2,allow_nan=False)+'\n',encoding='utf-8')
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def covariance(major,minor,pa):
    a=np.deg2rad(pa);u=np.array([np.sin(a),np.cos(a)]);v=np.array([np.cos(a),-np.sin(a)]);return (major**2*np.outer(u,u)+minor**2*np.outer(v,v))/(8*np.log(2))
def mapped_cov(beam):
    pa=np.deg2rad(144.);ci=np.cos(np.deg2rad(53.8623309521001));A=np.array([[np.sin(pa),np.cos(pa)],[np.cos(pa)/ci,-np.sin(pa)/ci]])*(3.611e3*np.pi/(180*3600));sky=covariance(30,30,0)-covariance(*beam);assert np.min(np.linalg.eigvalsh(sky))>0;return A@sky@A.T,A,sky
def gaussian(cov,dx):
    sizes=np.ceil(8*np.sqrt(np.diag(cov))/dx).astype(int);x=np.arange(-sizes[0],sizes[0]+1)*dx;y=np.arange(-sizes[1],sizes[1]+1)*dx;xx,yy=np.meshgrid(x,y,indexing='ij');inv=np.linalg.inv(cov);ker=np.exp(-.5*(inv[0,0]*xx*xx+2*inv[0,1]*xx*yy+inv[1,1]*yy*yy));ker/=ker.sum();return ker,xx,yy
def controls():
    cov,A,sky=mapped_cov((7.407,6.42384,71.79));assert np.max(abs(np.linalg.inv(A)@cov@np.linalg.inv(A).T-sky))<1e-10;k,x,y=gaussian(cov,.03125);moment=np.array([[np.sum(k*x*x),np.sum(k*x*y)],[np.sum(k*x*y),np.sum(k*y*y)]]);assert np.max(abs(moment-cov))<1e-10
    src=np.zeros((31,31));src[10:20,7:22]=np.arange(150).reshape(10,15);lap=np.exp(-abs(np.arange(-30,31))/4);lap/=lap.sum();a=fftconvolve(fftconvolve(src,k,mode='full'),lap[None,:],mode='full');b=fftconvolve(fftconvolve(src,lap[None,:],mode='full'),k,mode='full');err=float(np.max(abs(a-b))/np.max(abs(a)));assert err<1e-12
    rot=fftconvolve(src.T,k.T,mode='full').T;orig=fftconvolve(src,k,mode='full');assert np.max(abs(rot-orig))<1e-10
    return dict(covariance_moment_max_error=float(np.max(abs(moment-cov))),projection_convolution_commutation_relative=err,rotation=True,full_convolution_mass_relative=float(abs(orig.sum()/src.sum()-1)))
def main():
    out=P/'run001';out.mkdir(exist_ok=False);private=PRIVATE/'run001';private.mkdir(parents=True,exist_ok=False);spatial=R/'work/gravity-first-principles/mond-atlas-spatial-program-001/source-bindings.json';manifest=json.loads(spatial.read_text());cases=[c for c in manifest['source_cases'] if c['id'].startswith('f4')];comps={c['path']:c for ca in cases for c in ca['components']};generic=R/'work/private/mond-atlas-generic-source-001/run-002/nominal.npz';summary=R/'work/gravity-first-principles/mond-atlas-generic-source-001/run-002/summary.json';report=json.loads(summary.read_text());cfg=R/'configs/mond_atlas_source_resolution_v1.json';paths=[Path(__file__),P/'PREFLIGHT.md',spatial,generic,summary,cfg,R/'scripts/mond_atlas_source_resolution.py',R/'work/gravity-first-principles/mond-atlas-hi-column-001/source-alternatives-and-missingness.json']+[R/p for p in report['source_bindings']];bindings={str(p.relative_to(R)):digest(p) for p in paths}
    for path,c in comps.items():assert digest(R/path)==c['sha256'];bindings[path]=c['sha256']
    save(out/'bindings.json',bindings);save(out/'controls.json',controls());cohead=fits.getheader(R/'work/private/stellar-co-12gal-001/NGC2976__CO21_MOM0.fits.gz');hihead=fits.getheader(R/'work/private/things-observable-12gal-003/NGC_2976_NA_MOM0_THINGS.FITS');hist=[v for v in hihead['HISTORY'] if 'CLEAN BMAJ=' in v];assert len(hist)==1;beams={'stellar_luminosity':(2.1,2.1,0),'atomic_helium':(7.407,6.42384,71.79),'co21':(cohead['BMAJ']*3600,cohead['BMIN']*3600,cohead['BPA'])};save(out/'beam-assumptions.json',dict(beams=beams,hi_header_line=hist[0],stellar='Gaussian core approximation; non-Gaussian wings not matched',forward_inverse_native_PSF_deconvolution=False))
    records=[];assets=[];start=time.monotonic()
    for path,c in comps.items():
        with np.load(R/path) as packet:axis=packet['latent_axis'];source=packet['intrinsic_effective_surface'];obs=packet['observed_axis'];layers=packet['vertical_layers']
        cov,A,sky=mapped_cov(beams[c['id']]);projections=[]
        for factor in [1,2]:
            dx=.03125/factor;n=(len(axis)-1)*factor+1;nodes=np.linspace(axis[0],axis[-1],n);ss=zoom(source,(n/len(source),n/len(source)),order=1,mode='nearest',grid_mode=False,prefilter=False) if factor==2 else source.copy();assert ss.shape==(n,n)
            k,_,_=gaussian(cov,dx);full=fftconvolve(ss,k,mode='full');assert abs(full.sum()/ss.sum()-1)<1e-10;startx=k.shape[0]//2;starty=k.shape[1]//2;sm=full[startx:startx+n,starty:starty+n].copy();negative=float(-np.minimum(sm,0).sum());assert negative/max(ss.sum(),1)<1e-12;sm=np.maximum(sm,0);pre=sm.sum();sm[[0,-1],:]=0;sm[:,[0,-1]]=0;loss=float(1-sm.sum()/ss.sum());assert loss<1e-6
            left=cell_projection_matrix(obs,.125,nodes,dx,0);right=cell_projection_matrix(obs,.125,nodes,dx,float(layers[0,1])*np.tan(np.deg2rad(53.8623309521001)));proj=project(sm,left,right);projections.append(proj);filename=f'common30-{Path(path).stem}-q{factor}.npz';asset=private/filename;np.savez_compressed(asset,latent_axis=nodes,intrinsic_effective_surface=sm,vertical_layers=layers,observed_axis=obs,projected_surface=proj,additional_gaussian_covariance_kpc2=cov,assumed_native_beam_arcsec=beams[c['id']]);assets.append(dict(branch='common30_gaussian_approximation',component=c['id'],height_kpc=float(layers[0,1]),quadrature_factor=factor,path=asset.relative_to(R).as_posix(),sha256=digest(asset),conversion_to_msun_pc2=c['conversion_to_msun_pc2']));records.append(dict(branch='common30',component=c['id'],height_kpc=float(layers[0,1]),factor=factor,source_mass_before=float(ss.sum()*dx*dx*1e6*c['conversion_to_msun_pc2']),source_mass_after=float(sm.sum()*dx*dx*1e6*c['conversion_to_msun_pc2']),cropped_mass_fraction=loss,boundary_removed_fraction=float((pre-sm.sum())/ss.sum()),source_change_rms=float(np.linalg.norm(sm-ss)/np.linalg.norm(ss))))
        ref=float(np.linalg.norm(projections[1]-projections[0])/np.linalg.norm(projections[1]));assert ref<.002;records[-1]['coarse_fine_projection_rms']=ref;print('smoothed',c['id'],layers[0,1],flush=True)
    with np.load(generic) as packet:
        for component,height in [('stellar_luminosity',.1),('atomic_helium',.2),('co21',.2)]:
            obs=packet[component+'_axis'];mean=packet[component+'_mean'];coverage=packet[component+'_coverage'];annular=packet[component+'_annular'];xx,yy=np.meshgrid(obs,obs,indexing='ij');radius=np.hypot(xx,yy);trusted=np.isfinite(mean)&(coverage>=.5);nodes=np.linspace(obs[0],obs[-1],513);support=np.hypot(*np.meshgrid(nodes,nodes,indexing='ij'))<6;left=cell_projection_matrix(obs,.125,nodes,.03125,0);right=cell_projection_matrix(obs,.125,nodes,.03125,height*np.tan(np.deg2rad(53.8623309521001)));weight=(radius<5).astype(float)
            for fill in ['zero','annular']:
                target=np.where(trusted,np.maximum(np.nan_to_num(mean),0),0 if fill=='zero' else annular);source,fit=fit_fixed_image(target,weight,left,right,support,4,1e-4,12000,1e-6,backend='cupy');prediction=project(source,left,right);res=float(np.sqrt(np.sum(weight*(prediction-target)**2)/np.sum(weight*target**2)));asset=private/f'missing-{fill}-{component}.npz';np.savez_compressed(asset,latent_axis=nodes,intrinsic_effective_surface=source,vertical_layers=[[1.,height]],observed_axis=obs,projected_surface=prediction,imposed_target=target,imposed_weight=weight,original_trusted_mask=trusted,original_source_mean=mean,original_coverage=coverage);conversion=next(c['conversion_to_msun_pc2'] for c in comps.values() if c['id']==component);assets.append(dict(branch='missing_'+fill,component=component,height_kpc=height,path=asset.relative_to(R).as_posix(),sha256=digest(asset),conversion_to_msun_pc2=conversion,optimizer_converged=fit['converged']));save(out/f'optimizer-{fill}-{component}.json',fit);records.append(dict(branch='missing_'+fill,component=component,height_kpc=height,source_mass=float(source.sum()*.03125**2*1e6*conversion),imposed_target_rms=res,optimizer_converged=fit['converged'],iterations=fit['iterations'],trusted_cells=int(np.sum(trusted&(radius<5))),imposed_missing_cells=int(np.sum(~trusted&(radius<5))),positive_projection_negative_cells=int(np.sum(trusted&(radius<5)&(mean<0)))));print('fit',fill,component,fit['converged'],fit['iterations'],time.monotonic()-start,flush=True)
    save(out/'summary.json',dict(status='CONDITIONAL_SOURCE_ALTERNATIVES',records=records,assets=assets,seconds=time.monotonic()-start,observed_spectra_accessed=False,source_noise_likelihood=False,exact_common_PSF_claim=False))
if __name__=='__main__':
    with threadpool_limits(limits=1):main()
