"""The narrative skeleton of REPORT.md, with markers `report.py` fills from the
result JSONs.  Keeping the prose here rather than in a hand-edited Markdown
file is what makes every number in the report traceable to the file that
produced it.
"""

TEMPLATE = """# axis-2d — three separated power surfaces, and the two-dimensional shear test

Lane: `work/wellnet-2026-09/axis-2d/`
Code: `axis_power.py`, `selection.py`, `shear2d.py`, `amplitudes.py`,
`crosscheck.py`, `report.py`, `finalise.py`
Machine-readable: `axis_2d_results.json`, merging `axis_power.json`,
`selection.json`, `shear2d.json`, `amplitudes.json` and `crosscheck.json`.
This file is generated by `report.py` from those JSONs, so every number below
is read out of the file that produced it rather than transcribed.

<<HEADLINE>>

---

## 1. JOB 1 — three separated power surfaces

### 1.1 Why they had to be separated, and what separating them exposed

Run AC's near-spherical control injected the grammar's `dd` basis, which is
`dhat dhat^T` for a FIXED `dhat`. That is an EXTERNAL axis. A spherical source
under an external-axis tensor still has an anisotropic field, K is not
spherically symmetric, and the spherical blindness theorem does not cover it.
So Run AC's near-spherical row was never a test of the theorem, and its power
failing to collapse was the detector behaving correctly on a hypothesis the
theorem says nothing about. Separating the three provenances is not
bookkeeping; it is the difference between a control that means something and
one that does not.

`axis_power.py` gives each provenance its own arm, its own null distribution
and its own empirical critical value D*:

    source axis          w(I) x That            the source's own tidal tensor
    external tidal axis  w(I) x (d d^T - I/3)   five fixed directions spanning
                                                every constant symmetric
                                                traceless tensor
    member-well network  w(I) x N(x)            three catalogue orientations

with the scalar arm `w(I) x I` common to all. The statistic is

    D_p = RMS_oof(scalar atoms only) - RMS_oof(scalar + provenance-p atoms)

cross-fitted: the atom subset and its coefficients are chosen on one half of
the observable points and evaluated on the other, so a tensor atom cannot win
by mopping up a scalar interpolating function's error on the points it was
fitted to. The observable is genuinely two-dimensional — the midplane radial
acceleration plus BOTH components of the projected shear, never an azimuthal
average.

### 1.2 THE BUG THE THEOREM CAUGHT

The first version of this statistic used the raw tensor bases. Its source-axis
surface DID NOT COLLAPSE: power 0.42 / 0.62 / 0.24 at axis ratio 0.970 and
injected amplitude 0.35, flat in axis ratio and if anything rising. The brief
says that means a bug and the blindness theorem is the check. It was, and the
theorem says exactly where.

In spherical symmetry `ghat` is an eigenvector of any spherically symmetric K,
so

    K grad Phi_N = (ghat^T K ghat) grad Phi_N

— the tensor acts as a SCALAR rescaling with radial profile `ghat^T K ghat`.
That profile is not in the span of the bank's 70 scalar weights, so admitting
the tensor atoms genuinely improved the fit with no anisotropy anywhere. The
detector was measuring extra scalar flexibility and reporting it as a tensor.
The blindness theorem says the transverse eigenvalue is unobservable; it does
NOT say the tensor atom is unobservable, and the difference is the whole error.

The repair (`flux_orthogonal` in `axis_power.py`) redefines every non-identity
atom as

    K_perp = B - (ghat^T B ghat) I,      ghat^T K_perp ghat = 0

so its action on `grad Phi_N` has no component along `grad Phi_N`: it can only
TURN the flux, never rescale it. In exact spherical symmetry
`K_perp grad Phi_N` vanishes identically, so the source-axis atoms are exactly
null there and the surface must collapse — by construction rather than by
hope. The same construction disposes of the QUMOND degeneracy without a
special case: for `B = ghat ghat^T` the radial part is 1 and
`K_perp grad Phi_N = 0` identically.

The pre-repair run is kept in `prerepair/` rather than deleted, so the failing
control is auditable: `prerepair/axis_power_C.log` holds the 0.42 / 0.62 / 0.24
source-axis powers at axis ratio 0.970 that motivated the fix.

<<POWER_TABLES>>

### 1.6 Stage 0: what is in the null

Every null realisation carries all of the following at once, none of which is
in the atom bank:

* a scalar response drawn from FIVE qualitatively different families — an
  alternative interpolating function, a potential-depth gate, a mean-density
  gate, a tidal gate, and a nonlocal screened-fraction response — with random
  parameters;
* a TRIAXIAL BARYON DISTRIBUTION AT A RANDOM PROJECTION: the source that
  generates the data is not the source that built the bank (axis ratio
  perturbed by N(0, 0.05), sky-plane orientation by N(0, 12 deg));
* LINE-OF-SIGHT DEPROJECTION ERROR: the depth rescaled by lognormal(0.10);
* MISCENTERING: the mass offset from the assumed centre by N(0, 0.02 L) per
  axis;
* a RADIAL MASS-TO-LIGHT GRADIENT, N(0, 0.15) per scale radius;
* SHEAR-CALIBRATION ERROR: multiplicative m ~ N(0, 0.02) on both shear blocks
  and an additive c-term N(0, 0.01) on each;
* observation noise at the stated level.

Three disjoint simulation sets: CALIBRATION sims set D* as the 95th percentile
of the null statistic; UNTOUCHED AUDIT sims measure the realised false-positive
rate at that D*; INJECTION sims measure power. Over all
<<NFPR>> (arm, geometry, noise) cells the realised false-positive rate has
median <<FPRMED>> and mean <<FPRMEAN>>, range <<FPRMIN>> to <<FPRMAX>>, with
<<FPRFRAC>> per cent of cells inside 0.02-0.09 against a nominal 0.05 and a
binomial standard error of 0.011 at 400 audit draws. The detector is correctly
sized — measured, not asserted. Nine arms are calibrated simultaneously and a
family-wise critical value at 1 - 0.05/3 is carried alongside the per-arm
one.

WHAT IS NOT IN THE NULL, AND SHOULD BE. Line-of-sight structure (uncorrelated
haloes projected into the aperture), source-redshift error, and unresolved
member galaxies as a shape-measurement contaminant are not simulated. Those
are the three to add next.

### 1.7 Coarse-graining gate on the member-well tensor

<<COARSE>>

### 1.8 Monotonicity of the headline statistic

<<MONO>>

---

## 2. JOB 2 — the two-dimensional shear test

### 2.1 The construction

Azimuthally averaging a shear field discards almost all of its directional
content, which is why `g_t(R)` cannot separate a tensor from a mis-deprojected
triaxial baryon distribution: both move it the same way. The two-dimensional
field can, because the PHASE of the quadrupole is an independent observable
and the hypotheses put it in different places.

In a frame aligned with the independently measured member-light axis, a shear
quadrupole with a source-aligned part `a_src` and an external-axis part
`a_ext` at misalignment `Delta` decomposes as

    Q(phi) = [a_src + a_ext cos 2Delta] cos 2phi + [a_ext sin 2Delta] sin 2phi

so the SIN 2PHI COEFFICIENT IN THE SOURCE-ALIGNED FRAME IS A PURE
EXTERNAL-AXIS SIGNATURE, with a sign predicted by the measured misalignment.
Scalar gravity of any form, and a mis-deprojected triaxial baryon
distribution, both produce exactly zero there.

Per cluster i and radial bin b the harmonics `a0, a2c, a2s` come from a
weighted least squares of `e_t(phi)` on `(1, cos 2phi, sin 2phi)` WITH THE
ACTUAL AZIMUTHAL COVERAGE IN THE DESIGN, so a cluster near a mask edge is
handled exactly rather than by assuming `<cos^2 2phi> = 1/2`. The
metacalibration response `R = (R11+R22)/2` is recovered per radial bin from
the 1p/1m/2p/2m sheared copies rather than assumed. Then

    a2s(i,b) = alpha sin2Delta_i g_pred(i,b)   <- the tensor
             + beta  sin2Delta_i               <- uniform shear from neighbours
             + gamma                           <- additive c-term

The three columns separate by RADIAL DEPENDENCE: a real tensor quadrupole
scales with the cluster's own falling shear profile, while a uniform shear
leaking in from a neighbouring cluster is R-independent. That nuisance is not
a footnote — a neighbour's uniform shear `(gamma_1, gamma_2)` enters `e_t` as
`-(gamma_1 cos 2phi + gamma_2 sin 2phi)`, exactly the m = 2 mode being
measured, and it is aligned with the external axis BY CONSTRUCTION. It is the
one systematic that mimics the signal perfectly, so it is a fitted column.

`g_pred` is the monopole predicted from the baryons (Bahar+2022 Vikhlinin
electron-density fit, gas plus 15 per cent stars) through the RAR under no
slip. It is NOT the measured monopole, because regressing a measured
quadrupole on a measured monopole from the same sources puts the same noise on
both axes — this programme retracted `rho_p = -0.304` for exactly that.

`alpha`'s null is generated by RANDOMISING THE EXTERNAL AXIS 4000 times: the
member-light angle and every measured harmonic are left exactly as they are,
and only `pa_ext` is redrawn uniformly. That preserves the noise, the masks,
the systematics, the radial profile and the baryonic quadrupole, and destroys
only the thing the hypothesis is about.

The ellipticity-frame sign convention is the MEASURED one from
`../efeds-hsc/acquire_decade.py`: `phi = atan2(d_dec, -d_ra cos dec)`, first
axis WEST. It is used identically for member positions, neighbour positions
and source positions, so every phase difference is frame independent, and the
positive tangential monopole is a hard gate run before any quadrupole is
looked at.

### 2.2 The result

<<SHEAR_RESULT>>

### 2.3 Controls and gates

<<GATES>>

### 2.4 The regression-dilution trap, caught by end-to-end injection

The measured-monopole variant of the fit looked four times tighter. It is not
tighter, it is DILUTED. Injecting a known misaligned quadrupole into the real
measured harmonics and rerunning the whole fit gives a response slope

    d(recovered alpha) / d(injected alpha)  =  1.0000   predicted monopole
                                           =  0.0721   measured monopole
                                           =  1.0000   per-cluster fixed effects

The measured per-bin monopole is a noisy regressor, so its coefficient is
attenuated by a factor of about 14. Corrected, the measured-monopole form's
effective sensitivity is 3.7 times WORSE than the predicted-monopole form, not
4 times better. The apparently sharper number was an artefact, and the
injection test is what exposed it. It is also the numerical demonstration that
`dS/dtheta != 0` for the primary statistic.

---

## 3. JOB 3 — sample selection by independent geometry

### 3.1 The rule

Every quantity used to select is one of

* X-RAY: the eFEDS/Bahar+2022 catalogue — position, redshift, R500, gas mass,
  temperature, Vikhlinin density fit. Spherically symmetric by construction:
  it gives mass and scale, no axis.
* MEMBER LIGHT: the projected POSITIONS of DECADE galaxies whose photometric
  redshift places them at the cluster. Positions only — no shape, no
  ellipticity, no shear. The selection pass never requests a shape column from
  the archive; see `cache/decade_cache.manifest.json`.
* ENVIRONMENT: the projected tidal field at the target from the OTHER
  catalogued X-ray systems, weighted by their gas masses, `w = M_gas/d^3`
  (primary, the tidal weighting) with `w = M_gas/d^2` (the directionless
  inverse-square well strength) carried alongside.

The member slice `|z - z_cl| < 0.10 (1+z_cl)` and the scored background slice
`z > z_cl + 0.2` are DISJOINT BY CONSTRUCTION, so not one galaxy contributes
both a selection position and a scored shape. The margin is not marginal: the
highest member redshift is `z_cl + 0.10(1+z_cl)`, which at the sample's upper
redshift limit of 0.60 is `z_cl + 0.16`, still 0.04 below the background cut,
and 0.09 below it at the lower limit of 0.10.

### 3.2 The selection function, frozen

<<SELECTION>>

### 3.3 What is honest to flag about it

* NO X-RAY AXIS EXISTS FOR eFEDS in what is on disk. Bahar+2022 fit a
  spherically symmetric Vikhlinin model; the catalogue carries `ExtLike` but
  no ellipticity or position angle. The brief asked for "a well-measured
  member-galaxy OR X-ray axis" and the member-galaxy axis is what is
  available. The X-ray side contributes mass, scale and the environment map,
  not an axis. Stated plainly rather than substituted.
* THE DEVELOPMENT SAMPLE'S PER-CLUSTER ELLIPTICITIES ARE EDDINGTON-BIASED
  UPWARD. With a median of 43 photometric members the noise floor on the m = 2
  amplitude is `sqrt(2/N) = 0.22`, and selecting at `>= 2.5 sigma`
  preferentially picks upward fluctuations. The population moment is not
  biased: the deconvolved RMS member ellipticity is 0.276 over the whole
  parent, 0.584 for DEV and 0.000 for CTRL. The deconvolved value is what
  Job 4 uses.
* ONE CUT WAS CHANGED after the parent sample was measured and BEFORE any
  shear was computed. The control cut was first written on the raw m = 2
  amplitude at `<= 0.08`; with a noise floor of 0.22 that selects downward
  noise fluctuations rather than round clusters. It was changed to the
  noise-debiased amplitude at `<= 0.05`. The change is recorded in
  `selection.py` at the constant itself.
* THE MASK COULD IN PRINCIPLE COUPLE the selection to the phase statistic. If
  the survey footprint were aligned with the external axis, an error in
  `pa_mem` would correlate with `sin 2Delta`. Measured:
  `corr(sin2(pa_ext - pa_mask), sin 2Delta) = -0.176` over 386 systems, below
  the level at which it could drive the result.
* PHOTO-Z DILUTION IS NOT CORRECTED. DNF point estimates scatter cluster
  members into the background slice, which suppresses the measured monopole.
  Nothing here rests on the monopole normalisation: the phase statistic is a
  ratio of two shear quantities measured on the same sources, in which a
  multiplicative dilution factor cancels.

---

## 4. JOB 4 — amplitude translated into observables

### 4.1 Axis provenance across the whole tournament

Every one of the 3123 candidates in `../tournament/tournament.json` is
classified by the axis its anisotropy lives on. That is a property of the
STRUCTURE, not of the fitted amplitude:

| structure | K | lambda spread | provenance | candidates | survivors |
|---|---|---|---|---|---|
| `scalar_a0` | `a0 -> a0 (1 + A W)` | 0 | none | 783 with `iso_K` | 8 |
| `iso_K` | `exp(-A W) I` | 0 | none | — | — |
| `tensor_d` | `exp(A W (ghat ghat^T - I/3))` | 1 | source | 780 with `tensor_T` | 3 |
| `tensor_T` | `exp(A W That)` | 1.5 | source | — | — |
| `tensor_S` | `exp(A W S)`, S from the wells | 1 | network | 1560 | 7 |
| — | any FIXED EXTERNAL direction | — | external | **0** | **0** |

NOT ONE CANDIDATE IN THE TOURNAMENT CARRIES AN EXTERNAL TIDAL AXIS. That is
the single most important input to interpreting the two-dimensional null: the
hypothesis the phase test is built for is not represented in the grammar that
was searched.

### 4.2 Predicted amplitudes

`K = exp(A W S)` has eigenvalue ratio `exp(A W s)`, so the maximum fractional
acceleration anisotropy over the shear-measured shell (0.29 to 5.0 Mpc) is
`eps_K = |tanh(A W s / 2)|`, with W evaluated from the candidate's own
invariant on the real Bahar+2022 baryon profiles of the development clusters,
under the tournament's own declared primary boundary rule for `phi`. The
convergence ellipticity follows from the constant-K coordinate stretch,
`e_kappa = (sqrt(k1/k2) - 1)/(sqrt(k1/k2) + 1)` — exactly, not the
small-anisotropy `eps/2`, which is wrong by a factor 2 once `eps_K` approaches
1, as several survivors do. A source-axis or network tensor is purely radial
in the round limit and produces no quadrupole at all there, so its predicted
quadrupole carries the sample's deconvolved RMS member ellipticity as a
geometric factor. The coefficient turning `e_kappa` into an observed
quadrupole ratio is measured numerically on the real profile by putting an
elliptical convergence on a grid and taking its exact Fourier shear:
C = 0.440, flat to 1 per cent over `e = 0.02` to `0.20`.

ONE INHERITED NUMBER TO FLAG, NOT FIXED HERE. The amplitudes A are taken from
the tournament exactly as recorded, so they carry whatever conventions the
tournament used. Reading `tw_core.mond_invert`, the deep-MOND scaling of the
response tensor's radial eigenvalue appears to differ between its two base
laws: the `aqual` branch gives `g ~ sqrt(F a0) k^(-3/4)`, which is what its
docstring claims for both, while the `rar` branch, which uses the argument
`F/(k^1.5 a0)`, gives `g ~ sqrt(F a0) k^(-1/4)`. If that is right the fitted A
of a `rar`-based candidate is not on the same footing as its `aqual` twin —
consistent with the observed pattern, e.g. `rar|tensor_S|phi|pow|m1` at
A = -40.0 against `aqual|tensor_S|phi|pow|m1` at A = -25.5. It does not change
any conclusion in this lane, because none of them rests on a single
candidate's amplitude, but the eps_K column for `rar`-based rows should be
read with that caveat. It has been flagged as a separate task against the
tournament lane rather than patched from here.

<<AMPLITUDE_TABLE>>

### 4.3 Could this test have seen it?

<<COULD_SEE>>

---

## 5. Failure modes on the programme checklist — each checked explicitly

SHARED-DENOMINATOR ARTEFACTS. The design column is the monopole PREDICTED from
the X-ray baryons, not the measured one, so the same sources do not sit on both
axes. The residual noise correlation between the measured monopole and the
measured `sin 2phi` coefficient is measured, not assumed (Section 2.3). The
measured-monopole variant is reported anyway, with its regression dilution
measured by injection rather than assumed absent.

MONOTONE-INVARIANT STATISTICS. `dS/dtheta` is measured in two places: the power
surfaces are checked for dependence on amplitude, axis ratio and tilt with the
spreads printed (Section 1.8), and the two-dimensional statistic's response to
an injected signal in the real data is `d(recovered)/d(injected) = 1.0000`.

REFITTING ON THE HELD-OUT SET. The power statistic is cross-fitted: subset and
coefficients on one fold, evaluation on the other. The sample is frozen by
SHA-256 before any shear is computed and `shear2d.py` refuses to run if the
hash differs.

SILENT EXTRACTION FAILURES. `load_efeds` asserts 542 rows in each of the two
VizieR tables. Every TAP response is parsed with an explicit row-count floor
and the identifier is echoed per system. One raw upstream response per pass is
kept verbatim with its exact query. An early MemoryError in the CSV parser is
recorded in `selection.py` alongside the fix rather than silently patched.

TEST BUGS THAT LOOK LIKE SOLVER BUGS. The ellipticity-frame sign convention is
the measured one and the positive tangential monopole is a hard gate run
before any quadrupole is looked at. The lane's harmonic estimator is
cross-checked against the eFEDS lane's independently binned weighted-mean
profile (Section 2.3); the two share sources, so that is an
estimator-consistency check, not an independent measurement.

NON-MONOTONIC M(r) AND CLIPPED OUTER SLOPES. `dM_dyn/dr >= 0` inside the
truncation radius is checked for every system used (Section 2.3).

SPHERICAL BLINDNESS. Used as an active check, and it caught a real bug in the
statistic (Section 1.2).

CONSTANT-K DEGENERACY. Declared and used rather than fought: the conversion
from `eps_K` to a convergence ellipticity in Section 4.2 IS the coordinate
stretch. It is also why the amplitude channel cannot decide anything on its
own and why the phase channel exists.

COARSE-GRAINING INVARIANCE. Measured for the member-well tensor (Section 1.7).

THE SHELL AVERAGE OF A CONDUCTIVITY. This lane never shell-averages a
conductivity: the power surfaces use full three-dimensional solves and the
shear work is a projection of a measured field.

BOUNDEDNESS. Not re-tested; this lane measures detectability, not asymptotics.
The relevant consequence is inherited: `|S|_2 < 2/3` fixes the eigenvalue
spread used in Section 4.2.

POTENTIAL-GAUGE INVARIANCE. The `phi` invariant uses the tournament's own
declared primary rule so the amplitudes mean what they meant when they were
fitted. The alternative rules are not rescanned here.

RECIPROCITY AND ACTION. Not tested in this lane.

PROGRAMME-LEVEL MULTIPLICITY. Nine arms are calibrated simultaneously in Job 1
with a family-wise critical value carried alongside. In Job 2 the channels and
samples are five looks; no channel is significant, so no multiplicity
correction changes the conclusion.

SEALED HOLDOUTS. KiDS and wide binaries were never loaded, never queried,
never referenced.

NO DATA THAT PRESUPPOSES DARK MATTER. The observables are raw metacalibration
ellipticities and X-ray surface-brightness fits. No mass catalogue, no
convergence map and no NFW fit enters any number reported here.

THE SYNTHETIC-CATALOGUE TRAP. The Zenodo records titled "HSC Y3 Shape Catalog
— GAMA09H Full Field" (10.5281/zenodo.15482851 and two siblings) were NOT
downloaded, NOT used and NOT consulted. They describe exactly this field with
e1/e2/RA/Dec and are synthetic: the creator list includes an LLM simulation
assistant and the correction notice calls one of them "an algorithmically
scaled or pipeline-derived artifact". The exclusion is recorded in
`cache/decade_cache.manifest.json` under `NOT_USED`.

---

## 6. What this lane could NOT establish

<<COULD_NOT>>

---

## 7. Provenance

All network data comes from one unauthenticated endpoint,
`https://datalab.noirlab.edu/tap/sync`, table `delve_dr3.decade_shear` (the
DECADE metacalibration shape catalogue released in DELVE DR3), plus the
Bahar+2022 eFEDS tables already on disk in `../lead01/` with their own
manifests. The exact query templates, one verbatim raw response per pass, row
counts, SHA-256 digests and the list of things deliberately not used are in
`cache/decade_cache.manifest.json`. Source-file digests for every script are in
`axis_2d_results.json` under `source_sha256`.
"""
