"""JOB 2 -- THE TWO-DIMENSIONAL SHEAR TEST.  Amplitude AND phase.

Azimuthally averaging a shear field throws away almost all of its directional
content.  That is why the eFEDS lane, which is the right instrument for the
scalar question, cannot settle the tensor one: g_t(R) is a single number per
radius and a tensor, a triaxial baryon distribution and a deprojection error
all move it the same way.

The two-dimensional field does not have that problem, because the PHASE of the
shear quadrupole is an independent observable, and the three hypotheses put it
in different places:

    scalar gravity, whatever its form, and a mis-deprojected TRIAXIAL BARYON
        distribution, both put the quadrupole along the BARYONIC axis.  In a
        frame aligned with that axis they produce cos 2phi and NOTHING in
        sin 2phi.
    a tensor aligned with an EXTERNAL tidal axis puts a quadrupole at the
        external angle.  Decomposed in the source-aligned frame,

            Q(phi) = a_src cos 2phi + a_ext cos 2(phi - Delta)
                   = [a_src + a_ext cos 2Delta] cos 2phi
                     + [a_ext sin 2Delta] sin 2phi

        so the sin 2phi coefficient in the source-aligned frame is a PURE
        external-axis signature with a predicted sign, set by the measured
        misalignment Delta between the two independently measured axes.

THE STATISTIC.  For cluster i and radial bin b, in the frame aligned with the
member-light axis,

    A_s(i, b) = alpha * sin2Delta_i * g_pred(i, b)          <- the tensor
              + beta  * sin2Delta_i                          <- uniform shear
              + gamma                                        <- additive c-term

alpha is the headline.  The three columns are separated by their RADIAL
dependence: a real tensor quadrupole scales with the cluster's own shear
signal, which falls steeply with R, while a uniform shear leaking in from a
neighbouring cluster is R-independent -- and a neighbour's uniform shear is
aligned with the external axis BY CONSTRUCTION, so it is the one systematic
that mimics this signal exactly.  It is a fitted column, not a footnote.

WHY g_pred AND NOT THE MEASURED MONOPOLE.  Regressing a measured quadrupole on
a measured monopole from the SAME sources puts the same noise on both axes.
This programme retracted rho_p = -0.304 for exactly that.  So the design
column is the monopole PREDICTED from the baryons (the Bahar+2022 Vikhlinin
density fit) through the RAR under no slip -- a quantity the shear catalogue
never touches.  The measured-monopole version is computed alongside and its
noise correlation with A_s is reported.

CALIBRATION.  alpha's null is generated by RANDOMISING THE EXTERNAL AXIS: the
member-light angle, and therefore every measured harmonic, is left exactly as
it is, while the external position angle is redrawn uniformly, and the fit is
rerun 4000 times.  That preserves every property of the shear data -- its
noise, its masks, its systematics, its radial profile, its baryonic quadrupole
-- and destroys only the thing the hypothesis is about.  The p value is read
off that distribution, not from a chi-squared.

THREE CHANNELS ARE FITTED, NOT ONE.
    a2s   the phase-misaligned channel -- THE TEST.
    a2c   the source-aligned channel -- a POSITIVE CONTROL.  Elliptical
          baryons must show up here, and if they do not, the machinery is not
          measuring a quadrupole at all and a null in a2s means nothing.
    x2s   the same channel of the CROSS component -- a B-mode null that no
          lensing signal of any kind can produce.
and the whole thing is repeated on a near-round NEGATIVE CONTROL sample.

THE SIGN CONVENTION IS MEASURED, NOT ASSUMED.  phi = atan2(d_dec, -d_ra cos
dec): the DECADE/DES ellipticity basis has its first axis pointing WEST.  The
tangential monopole is required to come out POSITIVE as a gate before any
quadrupole is looked at; the other sign choice gives -0.002 instead of +0.011.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import io
import json
import math
import os
import ssl
import sys
import time
import urllib.parse
import urllib.request

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
LANE = os.path.dirname(HERE)
EFEDS = os.path.join(LANE, "efeds-hsc")
for p in (EFEDS, os.path.join(LANE, "lead01")):
    if p not in sys.path:
        sys.path.insert(0, p)

import pipeline as P                                            # noqa: E402
import efeds_hsc as E                                           # noqa: E402

CACHE = os.path.join(HERE, "cache")
os.makedirs(CACHE, exist_ok=True)

TAP = "https://datalab.noirlab.edu/tap/sync"
UA = "research/1.0 (gravity programme)"
CTX = ssl.create_default_context()
DGAMMA = 0.01

# ------------------------------------------------------------- DECLARED SETUP
NBIN = 6
RMIN_H, RMAX_H = 0.2, 3.5               # h^-1 Mpc, physical; Chiu+2022 range
DZ_BG = 0.20
THETA_CAP_DEG = 1.5
N_ROT = 4000                            # axis-randomisation null draws
F_STAR = 0.15                           # stellar mass as a fraction of M_gas

COLS = ("ra,dec,mcal_g_1_noshear,mcal_g_2_noshear,mcal_w_noshear,dnf_z,"
        "mcal_g_1_1p,mcal_g_1_1m,mcal_g_2_2p,mcal_g_2_2m")
SEL = ("mcal_flags = 0 AND flags_foreground = 0 AND flags_footprint = 1 "
       "AND mcal_sel_noshear > 0 AND dnf_z > 0 AND dnf_z < 3")


def tap(query, retries=4):
    body = urllib.parse.urlencode({"REQUEST": "doQuery", "LANG": "ADQL",
                                   "FORMAT": "csv", "QUERY": query}).encode()
    for k in range(retries):
        try:
            req = urllib.request.Request(TAP, data=body,
                                         headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=300, context=CTX) as r:
                return r.read()
        except Exception:                                       # noqa: BLE001
            if k == retries - 1:
                raise
            time.sleep(3 * (k + 1))


def parse_csv(raw):
    import pandas as pd
    df = pd.read_csv(io.BytesIO(raw))
    return list(df.columns), df.to_numpy(dtype=float)


def phi_west(ra_s, de_s, ra_c, de_c):
    d2r = math.pi / 180.0
    dra = (ra_s - ra_c) * math.cos(de_c * d2r)
    dde = de_s - de_c
    return np.arctan2(dde, -dra), np.hypot(dra, dde) * d2r


# ------------------------------------------------------- per-cluster harmonics
def harmonics(e, w, R, phi_rel, edges, resp):
    """Weighted least squares of e(phi) = a0 + a2c cos2phi + a2s sin2phi.

    Done per radial bin with the actual azimuthal coverage in the design, so a
    cluster near a mask edge is handled exactly rather than by assuming
    <cos^2 2phi> = 1/2.  Errors come from the WLS covariance with shape-noise
    weights; the full 3x3 covariance is returned so the monopole-quadrupole
    noise correlation can be inspected instead of assumed to vanish.
    """
    out = []
    for i in range(len(edges) - 1):
        m = (R >= edges[i]) & (R < edges[i + 1])
        n = int(m.sum())
        if n < 30:
            out.append(None)
            continue
        c2 = np.cos(2 * phi_rel[m])
        s2 = np.sin(2 * phi_rel[m])
        X = np.column_stack([np.ones(n), c2, s2])
        ww = w[m]
        y = e[m]
        XtW = X.T * ww
        A = XtW @ X
        try:
            Ainv = np.linalg.inv(A)
        except np.linalg.LinAlgError:
            out.append(None)
            continue
        beta = Ainv @ (XtW @ y)
        # shape-noise covariance: sum_j w_j^2 sigma_j^2 x_j x_j^T, with
        # sigma_j^2 estimated by the weighted variance of e in the bin
        var = float(np.sum(ww * (y - X @ beta) ** 2) / max(np.sum(ww), 1e-30))
        cov = Ainv @ ((X.T * (ww ** 2 * var)) @ X) @ Ainv
        r = resp[i] if resp[i] and abs(resp[i]) > 1e-3 else np.nan
        out.append(dict(n=n, R=float(np.sum(ww * R[m]) / np.sum(ww)),
                        a0=float(beta[0]) / r, a2c=float(beta[1]) / r,
                        a2s=float(beta[2]) / r,
                        e0=float(math.sqrt(max(cov[0, 0], 0))) / abs(r),
                        e2c=float(math.sqrt(max(cov[1, 1], 0))) / abs(r),
                        e2s=float(math.sqrt(max(cov[2, 2], 0))) / abs(r),
                        rho_0_2s=float(cov[0, 2]
                                       / math.sqrt(max(cov[0, 0] * cov[2, 2],
                                                       1e-300))),
                        R_metacal=float(r)))
    return out


def cluster_measure(rec, raw, edges_mpc):
    """Everything measurable from one cluster's background sources."""
    head, a = parse_csv(raw)
    if a.shape[0] < 200:
        return None
    col = {n: i for i, n in enumerate(head)}
    ra, de = a[:, col["ra"]], a[:, col["dec"]]
    e1, e2 = a[:, col["mcal_g_1_noshear"]], a[:, col["mcal_g_2_noshear"]]
    w = a[:, col["mcal_w_noshear"]]
    zs = a[:, col["dnf_z"]]
    e1p, e1m = a[:, col["mcal_g_1_1p"]], a[:, col["mcal_g_1_1m"]]
    e2p, e2m = a[:, col["mcal_g_2_2p"]], a[:, col["mcal_g_2_2m"]]
    z_l = rec["z"]
    phi, th = phi_west(ra, de, rec["RA"], rec["DE"])
    Rphys = th * rec["DA"] / P.MPC
    bg = (zs > z_l + DZ_BG) & (Rphys >= edges_mpc[0]) & (Rphys < edges_mpc[-1])
    if bg.sum() < 200:
        return None
    c2, s2 = np.cos(2 * phi), np.sin(2 * phi)
    et = -(e1 * c2 + e2 * s2)
    ex = (e1 * s2 - e2 * c2)
    # metacalibration response per radial bin
    resp = []
    for i in range(len(edges_mpc) - 1):
        m = bg & (Rphys >= edges_mpc[i]) & (Rphys < edges_mpc[i + 1])
        if m.sum() < 30:
            resp.append(np.nan)
            continue
        ww = w[m]
        sw = ww.sum()
        R11 = float(np.sum(ww * (e1p[m] - e1m[m])) / sw / (2 * DGAMMA))
        R22 = float(np.sum(ww * (e2p[m] - e2m[m])) / sw / (2 * DGAMMA))
        resp.append(0.5 * (R11 + R22))
    beta_s = np.where(zs > z_l, (P.d_com(zs) - P.d_com(z_l)) / (1.0 + zs)
                      / np.maximum(P.d_ang(zs), 1.0), 0.0)
    return dict(phi=phi[bg], R=Rphys[bg], et=et[bg], ex=ex[bg], w=w[bg],
                e1=e1[bg], e2=e2[bg], resp=resp,
                beta=float(np.sum(w[bg] * beta_s[bg]) / np.sum(w[bg])),
                beta2=float(np.sum(w[bg] * beta_s[bg] ** 2) / np.sum(w[bg])),
                n=int(bg.sum()))


# ------------------------------------------------- predicted monopole, no slip
def predicted_monopole(rec, R_mpc, beta, beta2):
    """g_+(R) from baryons + RAR under NO SLIP -- never from the shear itself.

    This is the column the phase statistic is regressed on, so it must not
    share any noise with the measurement.  It comes from the Bahar+2022
    Vikhlinin electron-density fit only.
    """
    sysm = P.System(rec, f_star=F_STAR)
    Rm = np.asarray(R_mpc) * P.MPC
    g = sysm.g_pred(law="rar")
    S, dS = sysm.sigma_profile(g, Rm, r_trunc_mpc=10.0)
    scr = P.CLIGHT ** 2 / (4.0 * math.pi * P.G * rec["DA"] * max(beta, 1e-6))
    kap, gam = S / scr, dS / scr
    corr = 1.0 + kap * (beta2 / max(beta, 1e-9) ** 2 - 1.0)
    return gam / np.maximum(1.0 - kap, 1e-3) * corr


# ----------------------------------------------------------------- the global fit
def fit_alpha(rows, key="a2s", use_pred=True, sin2d=None,
              with_sin2d=True, fixed_effects=False):
    """WLS for alpha, beta, gamma over every (cluster, radial bin).

    `key` selects the channel:
        a2s  the PHASE-MISALIGNED channel -- zero for any source-axis model,
             including a mis-deprojected triaxial baryon distribution.  This
             is the test.
        a2c  the source-aligned channel -- a positive control: elliptical
             baryons must produce a signal here.
        x2s  the same misaligned channel of the CROSS component, a B-mode
             null that no lensing signal can produce.

    `sin2d`, if given, replaces the measured sin 2Delta per cluster.  That is
    the null: randomising the EXTERNAL axis destroys the only thing the
    hypothesis is about while leaving every property of the shear -- its
    noise, its mask, its radial profile, its systematics -- exactly as
    measured.
    """
    ekey = {"a2s": "e2s", "a2c": "e2c", "x2s": "e2s"}[key]
    nc = len(rows)
    X, y, wgt = [], [], []
    for k, r in enumerate(rows):
        sd = (r["sin2delta"] if sin2d is None else float(sin2d[k]))             if with_sin2d else 1.0
        for b in r["bins"]:
            if b is None:
                continue
            v = b.get(key, np.nan)
            e = b.get(ekey, np.nan)
            if not np.isfinite(v) or not np.isfinite(e) or e <= 0:
                continue
            gp = b["g_pred"] if use_pred else b["a0"]
            if not np.isfinite(gp):
                continue
            if fixed_effects:
                # one intercept per cluster.  sin 2Delta is constant within a
                # cluster, so the uniform-shear column and every other
                # per-cluster systematic are absorbed exactly, and alpha is
                # identified ONLY by the RADIAL variation of g_pred inside each
                # object -- the standing brief's "system fixed effects".
                row = [sd * gp] + [0.0] * nc
                row[1 + k] = 1.0
            elif with_sin2d:
                row = [sd * gp, sd, 1.0]
            else:
                # no sin 2Delta factor: the source-aligned positive control,
                # where the baryonic quadrupole scales with the monopole and
                # NOT with the axis misalignment.  The sin 2Delta column would
                # be identical to the intercept here, so it is dropped rather
                # than left to make the normal equations singular.
                row = [gp, 1.0]
            X.append(row)
            y.append(v)
            wgt.append(1.0 / e ** 2)
    if len(y) < 8 + (nc if fixed_effects else 0):
        return None
    X = np.array(X)
    y = np.array(y)
    W = np.array(wgt)
    A = (X.T * W) @ X
    try:
        Ainv = np.linalg.inv(A)
    except np.linalg.LinAlgError:
        return None
    b = Ainv @ ((X.T * W) @ y)
    resid = y - X @ b
    chi2 = float(np.sum(W * resid ** 2))
    out = dict(alpha=float(b[0]),
               e_alpha=float(math.sqrt(max(Ainv[0, 0], 0))),
               chi2=chi2, dof=len(y) - X.shape[1], n=len(y),
               n_param=int(X.shape[1]))
    if not fixed_effects and with_sin2d:
        out.update(beta=float(b[1]), gamma=float(b[2]),
                   e_beta=float(math.sqrt(max(Ainv[1, 1], 0))),
                   e_gamma=float(math.sqrt(max(Ainv[2, 2], 0))),
                   corr_alpha_beta=float(Ainv[0, 1]
                                         / math.sqrt(max(Ainv[0, 0]
                                                         * Ainv[1, 1],
                                                         1e-300))))
    return out


def randomised_axes(rows, rng):
    """sin 2Delta with the EXTERNAL position angle drawn uniformly at random."""
    return np.array([math.sin(2 * (rng.uniform(0, math.pi)
                                   - math.radians(r["pa_mem_deg"])))
                     for r in rows])


def main():
    print("=" * 78)
    print("SHEAR 2D -- the quadrupole's PHASE, not just its amplitude")
    print("=" * 78)
    sel_path = os.path.join(HERE, "selection.json")
    blob = open(sel_path, "rb").read()
    h = hashlib.sha256(blob).hexdigest()
    frozen = open(sel_path + ".sha256", encoding="utf-8").read().strip()
    if h != frozen:
        raise SystemExit(f"selection.json has changed since it was frozen\n"
                         f"   on disk {h}\n   frozen  {frozen}")
    sel = json.loads(blob)
    print(f"\n   selection.json verified, SHA-256 {h[:16]}...")
    print(f"   DEV {len(sel['dev'])} systems, CTRL {len(sel['ctrl'])} systems")

    recs, _ = E.load_efeds()
    by_id = {r["id"]: r for r in recs}
    edges = np.geomspace(RMIN_H / P.H_LITTLE, RMAX_H / P.H_LITTLE, NBIN + 1)
    print(f"   {NBIN} radial bins over {edges[0]:.3f}-{edges[-1]:.3f} "
          f"proper Mpc")

    out = dict(generated_utc=dt.datetime.now(dt.timezone.utc)
               .strftime("%Y-%m-%dT%H:%M:%SZ"),
               selection_sha256=h, n_bins=NBIN,
               edges_mpc=[float(x) for x in edges],
               n_rot=N_ROT, samples={})
    raw_kept = False

    for tag in ("dev", "ctrl"):
        entries = sel[tag]
        print(f"\n   ---- {tag.upper()} : {len(entries)} systems")
        rows = []
        t0 = time.time()
        for j, s in enumerate(entries):
            rec = by_id[s["id"]]
            npz = os.path.join(CACHE, f"shear_{s['id']}.npz")
            if os.path.exists(npz):
                d = np.load(npz)
                meas = {k: d[k] for k in d.files}
                meas["resp"] = list(meas["resp"])
                meas["beta"] = float(meas["beta"])
                meas["beta2"] = float(meas["beta2"])
            else:
                rad = min(THETA_CAP_DEG,
                          edges[-1] * P.MPC / rec["DA"] * 180 / math.pi)
                q = (f"SELECT {COLS} FROM delve_dr3.decade_shear WHERE "
                     f"'t' = q3c_radial_query(ra, dec, {rec['RA']:.6f}, "
                     f"{rec['DE']:.6f}, {rad:.6f}) AND {SEL}")
                raw = tap(q)
                if not raw_kept:
                    with open(os.path.join(CACHE, "shear_raw_example.csv"),
                              "wb") as g:
                        g.write(raw)
                    with open(os.path.join(CACHE,
                                           "shear_raw_example.query.txt"),
                              "w", encoding="utf-8") as g:
                        g.write(q)
                    raw_kept = True
                meas = cluster_measure(rec, raw, edges)
                if meas is None:
                    print(f"      {s['id']}: too few background sources")
                    continue
                np.savez_compressed(
                    npz, **{k: np.asarray(v) for k, v in meas.items()})
            gp = predicted_monopole(
                rec, [0.5 * (edges[i] + edges[i + 1]) for i in range(NBIN)],
                meas["beta"], meas["beta2"])
            # frame S: reference axis = the member-light axis
            phi_rel = meas["phi"] - math.radians(s["pa_mem_deg"])
            hb = harmonics(meas["et"], meas["w"], meas["R"], phi_rel, edges,
                           meas["resp"])
            hx = harmonics(meas["ex"], meas["w"], meas["R"], phi_rel, edges,
                           meas["resp"])
            for i, b in enumerate(hb):
                if b is not None:
                    b["g_pred"] = float(gp[i])
                    b["x2c"] = hx[i]["a2c"] if hx[i] else np.nan
                    b["x2s"] = hx[i]["a2s"] if hx[i] else np.nan
                    b["x0"] = hx[i]["a0"] if hx[i] else np.nan
            rows.append(dict(id=s["id"], z=s["z"],
                             misalign_deg=s["misalign_deg"],
                             sin2delta=s["sin2delta"],
                             e_mem=s["e_mem_debiased"],
                             pa_mem_deg=s["pa_mem_deg"],
                             pa_ext_deg=s["pa_ext_deg"],
                             neighbour_shear=s["neighbour_shear"],
                             n_src=int(meas["n"]), bins=hb))
            if j % 10 == 0:
                print(f"      {j+1}/{len(entries)}  {s['id']}  "
                      f"{int(meas['n'])} sources  {time.time()-t0:.0f}s")
        print(f"      {len(rows)} usable, {time.time()-t0:.0f}s")
        if not rows:
            out["samples"][tag] = dict(n=0)
            continue

        # ---------- GATE: the tangential monopole must be positive
        num = den = 0.0
        for r in rows:
            for b in r["bins"]:
                if b and np.isfinite(b["a0"]) and b["e0"] > 0:
                    num += b["a0"] / b["e0"] ** 2
                    den += 1.0 / b["e0"] ** 2
        gt_mean = num / den
        gt_err = math.sqrt(1.0 / den)
        # the cross monopole, the standard systematics null
        num = den = 0.0
        for r in rows:
            for b in r["bins"]:
                if b and np.isfinite(b.get("x0", np.nan)) and b["e0"] > 0:
                    num += b["x0"] / b["e0"] ** 2
                    den += 1.0 / b["e0"] ** 2
        gx_mean, gx_err = num / den, math.sqrt(1.0 / den)
        print(f"      GATE  stacked tangential monopole "
              f"{gt_mean:+.5f} +- {gt_err:.5f}  "
              f"({gt_mean/gt_err:+.1f} sigma)")
        print(f"      NULL  stacked cross monopole      "
              f"{gx_mean:+.5f} +- {gx_err:.5f}  "
              f"({gx_mean/gx_err:+.1f} sigma)")

        # ---------- the phase statistic and its axis-randomisation null
        rng = np.random.default_rng(20260904)
        fits, nulls = {}, {}
        SPECS = [
            ("a2s_pred", "a2s", True, True, False,
             "PHASE-MISALIGNED, predicted monopole  (THE TEST)"),
            ("a2s_meas", "a2s", False, True, False,
             "PHASE-MISALIGNED, measured monopole   (REGRESSION-DILUTED, "
             "see crosscheck.py)"),
            ("a2s_fe", "a2s", True, True, True,
             "PHASE-MISALIGNED, per-cluster fixed effects"),
            ("a2c_baryon", "a2c", False, False, False,
             "SOURCE-ALIGNED quadrupole             (positive control)"),
            ("x2s_bmode", "x2s", True, True, False,
             "CROSS component, misaligned channel   (B-mode null)"),
        ]
        for tagk, key, up, wsd, fe, label in SPECS:
            f = fit_alpha(rows, key=key, use_pred=up, with_sin2d=wsd,
                          fixed_effects=fe)
            na = []
            if wsd:
                for _ in range(N_ROT):
                    g = fit_alpha(rows, key=key, use_pred=up,
                                  sin2d=randomised_axes(rows, rng),
                                  with_sin2d=True, fixed_effects=fe)
                    if g:
                        na.append(g["alpha"])
            na = np.array(na)
            fits[tagk] = f
            nulls[tagk] = na
            if f is None:
                print(f"      {label}: not enough data to fit")
                continue
            if na.size >= 10:
                p_two = float(np.mean(np.abs(na) >= abs(f["alpha"])))
                z = ((f["alpha"] - float(np.mean(na)))
                     / (float(np.std(na)) + 1e-300))
                print(f"      {label}")
                print(f"         alpha = {f['alpha']:+.4f} +- "
                      f"{f['e_alpha']:.4f}   (axis-randomisation sigma "
                      f"{np.std(na):.4f}, z = {z:+.2f}, p = {p_two:.4f})")
            else:
                print(f"      {label}")
                print(f"         alpha = {f['alpha']:+.4f} +- "
                      f"{f['e_alpha']:.4f}   (no axis randomisation: this "
                      f"channel does not use sin 2Delta)")
            if "beta" in f:
                print(f"         beta  = {f['beta']:+.5f} +- "
                      f"{f['e_beta']:.5f}   gamma = {f['gamma']:+.5f} +- "
                      f"{f['e_gamma']:.5f}   corr(a,b) = "
                      f"{f['corr_alpha_beta']:+.2f}")
            print(f"         chi2/dof = {f['chi2']/max(f['dof'],1):.2f} "
                  f"over {f['n']} (cluster, bin) rows")
        fit = fits["a2s_pred"]
        fit_meas = fits["a2s_meas"]
        rho = [b_["rho_0_2s"] for r in rows for b_ in r["bins"]
               if b_ is not None and np.isfinite(b_.get("rho_0_2s", np.nan))]
        if rho:
            print(f"      noise correlation between the monopole and the "
                  f"sin 2phi coefficient: median {np.median(rho):+.3f} "
                  f"-- measured, not assumed, because the measured-monopole "
                  f"form puts the same sources on both axes")
        s2d = np.array([abs(r["sin2delta"]) for r in rows])
        print(f"      |sin 2Delta| over the sample: median "
              f"{np.median(s2d):.3f}")
        # ---------- the amplitude, both frames
        amp = quadrupole_amplitude(rows)
        print(f"      stacked quadrupole in the member-aligned frame, per "
              f"unit PREDICTED monopole:")
        print(f"         a2c/g_pred = {amp['ratio_2c']:+.4f} +- "
              f"{amp['e_ratio_2c']:.4f}   (source-aligned)")
        print(f"         a2s/g_pred = {amp['ratio_2s']:+.4f} +- "
              f"{amp['e_ratio_2s']:.4f}   (phase-misaligned)")
        print(f"         a0 /g_pred = {amp['ratio_0']:+.4f} +- "
              f"{amp['e_ratio_0']:.4f}   (the cluster gap: baryons + RAR "
              f"under-predict the shear by this factor)")
        out["samples"][tag] = dict(
            n=len(rows), gt_monopole=gt_mean, gt_monopole_err=gt_err,
            gx_monopole=gx_mean, gx_monopole_err=gx_err,
            channels={k: dict(
                fit=fits[k],
                null_std=float(np.std(nulls[k])) if nulls[k].size else None,
                null_mean=float(np.mean(nulls[k])) if nulls[k].size else None,
                p_two_sided=(float(np.mean(np.abs(nulls[k])
                                           >= abs(fits[k]["alpha"])))
                             if fits[k] is not None and nulls[k].size else None))
                      for k in fits},
            median_abs_sin2delta=float(np.median(s2d)),
            monopole_quadrupole_noise_corr=(float(np.median(rho))
                                            if rho else None),
            amplitude=amp,
            clusters=[{k: v for k, v in r.items() if k != "bins"}
                      for r in rows],
            profile=stacked_profile(rows, edges))
    with open(os.path.join(HERE, "shear2d.json"), "w") as f:
        json.dump(out, f, indent=1, default=float)
    print("\n   written: shear2d.json")


def quadrupole_amplitude(rows):
    """Inverse-variance stack of a2c/g_pred and a2s/g_pred over the sample."""
    def stack(key, ekey):
        num = den = 0.0
        for r in rows:
            for b in r["bins"]:
                if b is None or not np.isfinite(b[key]) or b[ekey] <= 0:
                    continue
                gp = b["g_pred"]
                if not np.isfinite(gp) or gp <= 0:
                    continue
                v, e = b[key] / gp, b[ekey] / gp
                num += v / e ** 2
                den += 1.0 / e ** 2
        return (num / den, math.sqrt(1.0 / den)) if den > 0 else (np.nan,
                                                                 np.nan)
    r0, e0 = stack("a0", "e0")
    r2c, e2c = stack("a2c", "e2c")
    r2s, e2s = stack("a2s", "e2s")
    amp2 = r2c ** 2 + r2s ** 2 - e2c ** 2 - e2s ** 2
    return dict(ratio_0=r0, e_ratio_0=e0,
                ratio_2c=r2c, e_ratio_2c=e2c, ratio_2s=r2s, e_ratio_2s=e2s,
                amplitude_debiased=float(math.sqrt(max(amp2, 0.0))),
                phase_deg=float(0.5 * math.degrees(math.atan2(r2s, r2c))))


def stacked_profile(rows, edges):
    """Inverse-variance stacked a0, a2c, a2s per radial bin."""
    prof = []
    for i in range(len(edges) - 1):
        d = {}
        for key, ekey in (("a0", "e0"), ("a2c", "e2c"), ("a2s", "e2s")):
            num = den = 0.0
            for r in rows:
                b = r["bins"][i]
                if b is None or not np.isfinite(b[key]) or b[ekey] <= 0:
                    continue
                num += b[key] / b[ekey] ** 2
                den += 1.0 / b[ekey] ** 2
            d[key] = num / den if den > 0 else np.nan
            d["e_" + key] = math.sqrt(1.0 / den) if den > 0 else np.nan
        gp = [r["bins"][i]["g_pred"] for r in rows
              if r["bins"][i] is not None]
        d["R_mpc"] = float(math.sqrt(edges[i] * edges[i + 1]))
        d["g_pred_mean"] = float(np.mean(gp)) if gp else np.nan
        d["n_clusters"] = len(gp)
        prof.append(d)
    return prof


if __name__ == "__main__":
    main()
